name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  major-version: 1
  minor-version: 0
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
#         source-url: https://nuget.pkg.github.com/HK-Zhang/index.json
#       env:
#         NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Output Run ID
      run: echo ${{env.major-version}}.${{env.minor-version}}.${{github.run_number}}
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore --configuration Release /p:Version=${{env.major-version}}.${{env.minor-version}}.${{github.run_number}} /p:PackageVersion=$version
#     - name: Create the package
#       run: dotnet pack --configuration Release /p:Version=$version /p:PackageVersion=$version
#     - name: Publish packages to GPR
#       run: dotnet nuget push */bin/Release/*.nupkg
#     - name: Publish packages to nuget
#       run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
#       env:
#         NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
