name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  version: 1.0.${{github.run_number}}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
#         source-url: https://nuget.pkg.github.com/HK-Zhang/index.json
#       env:
#         NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Version=${{env.version}} /p:PackageVersion=${{env.version}}
    - name: Create the package
      run: dotnet pack --configuration Release /p:Version=${{env.version}} /p:PackageVersion=${{env.version}}
    - name: Publish packages to GPR
      run: dotnet nuget push */bin/Release/*.nupkg -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/HK-Zhang/index.json
    - name: Publish packages to nuget
      run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
